# Site settings
title: "Mosby"
description: "Just a simple writing theme."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://craveiro.com.br/mosby" # the base hostname & protocol for your site
logo: "/assets/images/theme/logo.png"
image: "/assets/images/theme/blog-cover.jpg"
lang: pt_BR # The language that your posts are written
favicon: "/assets/images/theme/favicon.png"
analytics: ""
version: "4.1.0"

# Author settings
author:
  name: "Ted Mosby"
  email: "tedmosby@himym.com"
  description: "Just a guy looking for his soulmate."
  twitter: tedmosby
  picture: "/assets/images/theme/avatar.jpg"

# Social settings
twitter_username: raulcraveiro
youtube_username: raulcraveiro
instagram_username: raulcraveiro
linkedin_username: raulcraveiro
pinterest_username: raulcraveiro

# Twitter Cards
twitter:
  username: raulcraveiro
  card: summary_large_image

# Webmasters Settings
webmaster:
  google:
  bing:
  yandex:

# Mailchimp Settings
mailchimp_link: ""

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "page/:num/"

# Minification
sass:
  style: compressed

defaults:
  # Posts
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      author: raulcraveiro
  # Pages
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
