# Configurações do site
title: "Mosby" #Título do site
description: "Just a simple writing theme." #Descrição do site
baseurl: "" # Base do seu blog. Deixe em branco se quiser que o seu blog fique no domínio raiz.
url: "https://jekyll-mosby-theme.netlify.app" # URL do seu site
logo: "/assets/images/theme/logo.png" # Logo
image: "/assets/images/theme/blog-cover.png" # Imagem de capa (utilizada em compartilhamento para redes sociais)
lang: pt_BR # Linguagem que seus posts serão escritos
favicon: "/assets/images/theme/favicon.png" #Favicon do seu site
version: "4.1.0"

# Configurações do autor
author:
  name: "Ted Mosby" # Nome do autor
  email: "tedmosby@himym.com" # E-mail do autor
  description: "Just a guy looking for his soulmate." # Descrição do autor
  twitter: tedmosby # Usuário do Twitter do autor
  picture: "/assets/images/theme/avatar.jpg" # Imagem do autor

# Configurações de redes sociais
twitter_username: raulcraveiro # Usuário do Twitter
youtube_username: raulcraveiro # Usuário do YouTube
instagram_username: raulcraveiro # Usuário do Instagram
linkedin_username: raulcraveiro # Usuário do LinkedIn
pinterest_username: raulcraveiro # Usuário do Pinterest

# Twitter Cards
twitter:
  username: raulcraveiro # Usuário do Twitter
  card: summary_large_image

# Configurações de webmaster
webmaster:
  google:
  bing:
  yandex:

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "page/:num/"

# Minification
sass:
  style: compressed

defaults:
  # Posts
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      author: raulcraveiro
  # Pages
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
