## 301

  [[redirects]]

  from = "/mail"
  to = "https://mail.yandex.com/"
  status = 301

  [[redirects]]

  from = "/newsletter"
  to = "https://mailchi.mp/c3a41b56bb8e/cadastro"
  status = 301

  [[redirects]]

  from = "/twitter"
  to = "https://twitter.com/raulcraveiro"
  status = 301

  [[redirects]]

  from = "/instagram"
  to = "https://instagram.com/raulcraveiro"
  status = 301
  
  [[redirects]]

  from = "/discord"
  to = "https://discord.gg/bp8ArnG"
  status = 301

## 302

## Plugins

[[plugins]]
  package = "netlify-plugin-jekyll-cache"
  
  [plugins.inputs]
    # This is only required if you have defined a source directory in Jekyll
    # At some point this will become automated, but for now it must be specified 
    jekyllSource = ""
