backend:
  name: git-gateway
  branch: master
  use_large_media_transforms_in_media_library: false
  
publish_mode: editorial_workflow

media_folder: /assets/images
public_folder: /assets/images

collections:
  - name: "posts"
    label: "Blog"
    folder: "_posts"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "poemas"
    label: "Poemas"
    folder: "_poemas"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}